### ISSUE TITLE
[issue] admission-controller image is not changed according to the AlamedaService spec

### ISSUE THREAD

**Issue by mamafun** [containers-ai/federatorai-operator#126]
admission-controller image is not changed according to the AlamedaService spec

```
apiVersion: federatorai.containers.ai/v1alpha1
kind: AlamedaService
metadata:
  name: my-alamedaservice
  namespace: alameda
spec:
  enableexecution: true
  enablegui: true
  version: latest
  prometheusservice: http://prometheus-prometheus-oper-prometheus.monitoring:9090
  admission-controller:
    image: quay.io/prophetstor/alameda-admission-ubi
    imagePullPolicy: Always
```
