### ISSUE TITLE
FederatorAI Operator does not deploy Grafana if AlamedaService CR set enableGUI to true and enableExecution to false

### ISSUE THREAD

**Issue by mamafun** [containers-ai/federatorai-operator#64]
FederatorAI Operator does not deploy Grafana if AlamedaService CR set enableGUI to true and enableExecution to false.
The tested CR is:

```
apiVersion: v1
items:
- apiVersion: federatorai.containers.ai/v1alpha1
  kind: AlamedaService
  metadata:
    name: my-alamedaservice
    namespace: alam
  spec:
    enableexecution: false
    enablegui: true
    persistentvolumeclaim: ""
    prometheusservice: https://prometheus-k8s.openshift-monitoring:9091
    version: v0.3.7
```
